# Generated by Django 6.0.4 on 2026-04-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название товара', max_length=255, verbose_name='Название товара')),
                ('description', models.TextField(blank=True, help_text='Подробное описание товара', verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена товара в рублях', max_digits=10, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение товара', null=True, upload_to='products/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
    ]
